### PR TITLE
Compressed module support

### LINKED ISSUE #38: Compressed modules (*.ko.gz)
I installed a patch for alx.ko module and i noticed the original module is alx.ko.gz, but DKMS puts alx.ko into /lib/modules/4.13.12-1-ARCH/kernel/drivers/net/ethernet/atheros/alx/ thus kernel is loading the wrong module!

How can i make DKMS create and replace the alx.ko.gz module?

I'm running Arch Linux.

### PR DESCRIPTION
**Pull request by d3matt**
Should resolve #38

### CODE REVIEW

**Comment by d3matt** [comment]
Realized there are a couple more cases it needs to handle. Will update PR tommorow.

**Comment by scaronni** [comment]
Hello @d3matt, is this finished? Is your latest commit referred to the above comment?

Thanks.

**Comment by d3matt** [comment]
I think there's still some interaction between weak-modules and dkms for the mixed case (kernels with compressed modules and kernels with uncompressed modules installed), but I haven't been able to pinpoint what's going on there. My gut feeling is that weak-modules needs an update as well, but I don't have evidence to point in that direction. This PR is probably ready to be merged, but someone else might want to play with it as well.

**Comment by scaronni** [comment]
Thanks, will try it soon.

**Comment by scaronni** [comment]
Works perfectly. Sorry for the delay.

**Pull request merged**
