### PR TITLE
run_tests: saner handling of sig key/hashalgo

### PR DESCRIPTION
**Pull request by evelikov**
Namely request the field we're interested in.

Aka use `modinfo -F foobar` instead of `modinfo | grep foobar| sed 's/foobar://'` and alike.

@xuzhen can you double-check I'm not missing anything?

### CODE REVIEW

**Comment by evelikov** [comment]
Hmm stumbled upon the kmod built without openssl. Seems like the proper fix is to actually check  for the algo first - if unknown, then skip the key check. The current tests (at least) seem to be backwards.

**Comment by evelikov** [comment]
Pardon for the noise - trying to track down which piece of the stack is borked and thus srcversion is not produced. The original comment was saying Debian, although I suspect it could be kernel version related ... or patch thereof.

kmod itself doesn't even know about that field.

**Comment by evelikov** [comment]
The srcversion seems semi-magical and semi-broken atm - opened an issue for it https://github.com/dell/dkms/issues/311.

The updated PR, should do a saner handing of sig key/hashalgo now ... even though it started with a simple modinfo -F simplification :sweat_smile:

**Comment by xuzhen** [comment]
I think it's ready to merge.

**Pull request merged**
