### PR TITLE
Makefile: also install in /etc the kernel_install.d_dkms and sign_hel…

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
…per.sh scripts

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
TODO: should we also install them with debian and redhat targets?

**Comment by scaronni** [comment]
> TODO: should we also install them with debian and redhat targets?

Yes please. Thanks.

**Comment by LocutusOfBorg** [comment]
Rebased and pushed!

**Comment by LocutusOfBorg** [comment]
thanks!

**Pull request merged**
