### PR TITLE
Correct searching for rpm in PATH

### PR DESCRIPTION
**Pull request by hadogenes**
Signed-off-by: Jacek Szafarkiewicz <szafar@linux.pl>

### CODE REVIEW

**Comment by evelikov** [comment]
The commit message is very misleading - the searching is the same, the output redirection is changed.
Something like "dkms: redirect stderr to null during rpm detection" would be a better fix. @hadogenes can you please re-spin?

**Comment by xuzhen** [comment]
The ```elif [ `which rpm 2>/dev/null` ]; then``` just checks if rpm file exists. We can use ```elif which rpm &>/dev/nul; then``` or ```elif command -v rpm &>/dev/nul; then``` instead

**Comment by hadogenes** [comment]
> The commit message is very misleading - the searching is the same, the output redirection is changed. Something like "dkms: redirect stderr to null during rpm detection" would be a better name. @hadogenes can you please re-spin?

But ```[ `which rpm >/dev/null` ]``` is always false (`[ ]` test is checking if string is not empty and when we add `> /dev/null`, then test always false)

**Comment by evelikov** [comment]
@hadogenes sorry for misleading you there - you're right this fixes the check, but as a whole the existing code is subpar. Can you please follow [xuzhen's advice](https://github.com/dell/dkms/pull/259#issuecomment-1283290237) - thanks in advance.

**Comment by evelikov** [comment]
Fixed up myself, thanks for the great suggestion xuzhen.

**Pull request merged**
